### ISSUE TITLE
Error in creating variation graph

### ISSUE THREAD

**Issue by priyambial123** [SandraLouise/SVJedi-graph#2]
Hello,

I tried to create a variation graph using the vcf data from this link: https://ftp.ncbi.nlm.nih.gov/pub/dbVar/data/Homo_sapiens/by_study/vcf/nstd162.GRCh38.variant_call.vcf.gz. Please find the below command and error message

```
svjedi-graph.py -v nstd162.GRCh38.variant_call.vcf -r "/reference/human_GRCh38_no_alt_analysis_set.fasta" -q "/m64156_230613_232726.hifi_reads.fastq.gz" -q "/m64156_230504_074854.hifi_reads.fastq.gz" -p vcf

Constructing variation graph...
Traceback (most recent call last):
  File "/svjedi/bin/construct-graph.py", line 636, in <module>
    main(sys.argv[1:])
  File "/svjedi/bin/construct-graph.py", line 188, in main
    if end_on_chr >= len(d_chrom[chrom]) - 1 or start_on_chr >= len(d_chrom[chrom]) - 1:
                         ~~~~~~~^^^^^^^
KeyError: '1'
Mapping reads on graph...
[ERROR] failed to load the graph from file 'test1.gfa'
Filtering alignment file...
Traceback (most recent call last):
  File "/svjedi/bin/filter-alignments.py", line 631, in <module>
    main(sys.argv[1:])
  File "/svjedi/bin/filter-alignments.py", line 112, in main
    with open(gfa_file, "r") as graph_file:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test1.gfa'
Genotyping SVs...
Traceback (most recent call last):
  File "/svjedi/bin/predict-genotype.py", line 424, in <module>
    main(sys.argv[1:])
  File "/svjedi/bin/predict-genotype.py", line 77, in main
    with open(aln_dict_file, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test1_informative_aln.json'
```

**Comment by clemaitre** [comment]
Hi,

Can you check if the chromosomes are reported with the same names in your vcf file and in your fasta file (reference genome) ? The error message indicates that chromosome '1' is not found in your fasta file.

By the way, quotes around file paths are not necessary in the command line.

Best,
Claire

**Comment by priyambial123** [comment]
Hi Claire,

The reference used to call the variants in the vcf was not the same. So, I downloaded another data set, with same reference used to generate the vcf and now it runs fine

Thank you

**Comment by clemaitre** [comment]
Great !
Thanks to your issue we have updated the code so that the error message in this case is more explicit.

Best regards,
Claire
